version: 0.2
env:
  variables:
    REPOSITORY_URI: 837578041534.dkr.ecr.us-east-1.amazonaws.com/datacanvas-frontend-dev
    VITE_AWS_REGION: us-east-1
    VITE_AWS_COGNITO_OAUTH_DOMAIN: datacanvas.auth.us-east-1.amazoncognito.com
    VITE_SSO_REDIRECT_URI: https://devdatacanvaswf.cisco.com
    VITE_AMPLIFY_USERPOOL_ID: us-east-1_zsqRXIlpZ
    VITE_AMPLIFY_WEBCLIENT: 5bh0nl3t3l0hf8ubbhhoniocu1
    VITE_API_BASE_URL: https://devdatacanvaswf.cisco.com
    VITE_ENV: dev
    VITE_THOUGHTSPOT_HOST: https://cisco-dev.thoughtspot.cloud/
    VITE_THOUGHTSPOT_AUTH_TYPE: SSO_SAML

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:

  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
      # Remove any existing .env files, these are read as part of the build process
      - find . -type f -name ".env" -o -name ".env.*" -exec rm -f {} \;
      - echo "VITE_AWS_REGION=${VITE_AWS_REGION}" > .env
      - echo "VITE_AWS_COGNITO_OAUTH_DOMAIN=${VITE_AWS_COGNITO_OAUTH_DOMAIN}" >> .env
      - echo "VITE_SSO_REDIRECT_URI=${VITE_SSO_REDIRECT_URI}" >> .env
      - echo "VITE_AMPLIFY_USERPOOL_ID=${VITE_AMPLIFY_USERPOOL_ID}" >> .env
      - echo "VITE_AMPLIFY_WEBCLIENT=${VITE_AMPLIFY_WEBCLIENT}" >> .env
      - echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" >> .env
      - echo "VITE_THOUGHTSPOT_HOST=${VITE_THOUGHTSPOT_HOST}" >> .env
      - echo "VITE_THOUGHTSPOT_AUTH_TYPE=${VITE_THOUGHTSPOT_AUTH_TYPE}" >> .env
      # Ensure that the build will not fail due to warnings
      - echo "TSC_COMPILE_ON_ERROR=true" >> .env
  build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 837578041534.dkr.ecr.us-east-1.amazonaws.com
      # run build script
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:$PACKAGE_VERSION .
      # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$PACKAGE_VERSION

artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - .env
