from sqlalchemy import Column, Date, ForeignKey, Integer, Sequence, String, Table, func

from ..base import V2MetadataBase

MacdHdrTable = Table(
    "dc_wf_macd_upload_hdr",
    V2MetadataBase.metadata,
    Column(
        "request_id",
        Integer,
        server_default=Sequence("seq_dc_request").next_value(),
        primary_key=True,
    ),
    Column(
        "dc_engagement_id", Integer, ForeignKey("dc_engagement_hdr.dc_engagement_id")
    ),
    Column("dc_user_id", Integer, ForeignKey("dc_users.user_id")),
    Column(
        "sign_off_identity_id",
        Integer,
        ForeignKey("dc_typ_sign_off_identity.sign_off_identity_id"),
    ),
    Column("staged_file_uri", String(), comment="S3 URI of the staged file"),
    Column(
        "snowflake_file_uri",
        String(),
        comment="Snowflake normalized URI of the staged file",
    ),
    Column(
        "row_count",
        Integer,
        default=0,
        server_default="0",
        comment="Number of rows corresponding to this request and tracked in the dc_wf_macd_upload_detail table",
    ),
    Column("approved_by", String()),
    Column("effective_date", Date),
    Column("tool_name", String()),
    Column("tool_action", String()),
    Column("notes", String()),
    Column("created_by", String()),
    Column("create_dtm", Date, server_default=func.current_date()),
    Column("update_dtm", Date),
    Column("updated_by", String()),
    Column("is_deleted", String(1), default="F", server_default="F"),
)

MacdDetailTable = Table(
    "dc_wf_macd_upload_detail",
    V2MetadataBase.metadata,
    Column(
        "request_id",
        Integer,
        ForeignKey("dc_wf_macd_upload_hdr.request_id"),
        primary_key=True,
    ),
    Column("tool_name", String()),
    Column("tool_action", String()),
    Column("service_level", String()),
    Column("end_date", Date),
    Column("source_contract_number", String()),
    Column("source_service_level", String()),
    Column("begin_date", Date),
    Column("product_id", String()),
    Column("site_id", String()),
    Column("justification_reason", String()),
    Column("source_site_id", String()),
    Column("target_site_id", String()),
    Column("target_contract_number", String()),
    Column("end_customer_site_id", String()),
    Column("reason_code", String()),
    Column("cs_case_number", String()),
    Column("start_date", Date),
    Column("mpo", String()),
    Column("mso", String()),
    Column("quantity", Integer),
    Column("service_begin_date", Date),
    Column("service_end_date", Date),
    Column("covered_line_number", String()),
    Column("source_instance_id", String()),
    Column("source_serial_number", String()),
    Column("target_instance_id", String()),
    Column("target_serial_number", String()),
    Column("instance_status", String()),
    Column("rma_number", String()),
    Column("is_deleted", String(1), default="F", server_default="F"),
    Column("create_dtm", Date, server_default=func.current_date()),
    Column("update_dtm", Date),
    Column("updated_by", String()),
)
